name: Atualizar Custo de Vida Mensal

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar Repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Dependências
        run: |
          pip install requests beautifulsoup4

      - name: Executar Scraper
        run: python coletor.py

      - name: Salvar e Commitar Mudanças
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add paises.json
          git commit -m "Auto: Dados de custo de vida atualizados [skip ci]" || exit 0
          git push
